managerproject/managerproject/managerapp/urls.py
from django.urls import path
from .import views

app_name='managerapp'

urlpatterns = [
    path('',views.account,name='account'),
    path('index/',views.index,name="index"),

        #  ---------CreateTask------
    # path('Create-Task', views.CreateTask, name="Create-Task"),

    # path('user-logout', views.user_logout, name="user-logout"),
]

managerproject/managerproject/managerproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('managerapp.urls')),
    path('projects/', include('project.urls')),

]

managerproject/managerproject/project/urls.py
from django.urls import path

from .import views

app_name='project'

urlpatterns = [
    path('',views.projects, name='projects'),
    path('add/', views.add_project, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
]

managerproject/managerproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('managerapp.urls')),
]

managerproject/managerproject/managerapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

# class Task(models.Model):
#     name = models.CharField(max_length=100)
#     description = models.TextField()
#     assigned_person = models.ForeignKey(User, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.name


from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    assigned_person = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class TaskLog(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    log_entry = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.task.name} - {self.log_entry} - {self.timestamp}"

managerproject/managerproject/project/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.



class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

managerproject/managerproject/managerapp/forms.py
from django import forms
from django.contrib.auth.models  import User

from .models import Task


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    username=forms.CharField(error_messages='',max_length=100)
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    
    class Meta:
        model=User
        fields=('username','email')
    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password']!=cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
    

class CreateTaskForm(forms.ModelForm):

    class Meta:

        model = Task
        fields = ['name', 'description',]
        exclude = ['assigned_person',]

managerproject/managerproject/managerapp/views.py
from django.shortcuts import render,redirect

# Create your views here.
from managerapp.forms import LoginForm, UserRegistrationForm, CreateTaskForm
from django.contrib.auth import login, authenticate



# Create your views here.
def index(request):
    return render(request,'main/index.html')




def account(request):

    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        form = LoginForm(request.POST)
        
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return redirect('managerapp:account')
        # Note: You can use 'elif' instead of 'if' here
        elif form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])  # Fix password retrieval
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('managerapp:index')
                else:
                    return render(request, 'main/indexstart.html', {'form': form})
            else:
                return render(request, 'main/indexstart.html', {'form': form})
    else:
        user_form = UserRegistrationForm()
        form = LoginForm()
            
    return render(request,'main/indexstart.html', {'user_form': user_form, 'form': form})  # Pass both forms to the template

    #return render(request,'main/indexstart.html')


 #  ---------CreateTask------
# def CreateTask(request):
#     form = CreateTaskForm()

#     if request.method == 'POST': 
#        form = CreateTaskForm(request.POST)

#        if form.is_valid():
#            form.save()

#            return redirect('')
#     context = {'form': form}

#     return render(request, 'main/tasks_list.html', context=context)
 

managerproject/managerproject/project/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Project

from django.http import Http404
# Create your views here.

@login_required
def projects(request):
    projects = Project.objects.filter(created_by=request.user)

    return render(request, 'project/projects.html', {
        'projects': projects
    })

@login_required
def project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'project/project.html', {
        'project': project
    })

@login_required
def add_project(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description','')

        if name:
            Project.objects.create(name=name, description=description, created_by=request.user)

            return redirect('/projects/')
        else:
            print('Not valid')

    return render(request, 'project/add.html')

managerproject/managerproject/managerapp/templates/main/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>task management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary bg-gradient ">
        <div class="container-fluid">
          <a class="navbar-brand fw-bold text-white fs-3" href="#">task management system</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'project:projects' %}">project</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'managerapp:account' %}">Logout</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled fw-medium" aria-disabled="true">Disabled</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
    </nav>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Assigned person</th>
            </tr>
        </thead>

        <tbody>

        </tbody>
    </table>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

managerproject/managerproject/managerapp/templates/main/indexstart.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>task management system</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient b-5">
        <div class="container-fluid">
          <a class="navbar-brand"> project managers</a>
          <form class="d-flex" role="search">
            
            
            <!-- <a class="navbar-brand" href="#">Account</a> -->
          </form>
        </div>
    </nav>
<br>
<br>
      <!-- login area start -->
      <div class="login-register-area pt-100px pb-100px">
        <div class="pagination justify-content-center ">
            <div class="row">
                <div class=" col-md-12 ml-auto mr-auto  p-3">
                    <div class="login-register-wrapper">
                        <div class="login-register-tab-list nav gap-3">
                            <a class="active" data-bs-toggle="tab" href="">
                                <h4 class="btn btn-outline-secondary">login</h4>
                            </a>
                            
                            <a data-bs-toggle="tab" href="#lg2">
                                <h4 class="btn btn-outline-secondary">register</h4>
                            </a>
                        </div>
                        <div class="tab-content">
                            <div id="lg1" class="tab-pane active">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            {{ form.as_p }}

                                            <!-- <input type="text" name="user-name" placeholder="Username" />
                                            <br>
                                            <br>
                                            <input type="password" name="user-password" placeholder="Password" /> -->
                                            <div class="button-box">
                                                <div class="login-toggle-btn">
                                                    <input type="checkbox" />
                                                    <a class="flote-none" href="javascript:void(0)">Remember me</a>
                                                    <a href="#">Forgot Password?</a>
                                                </div>
                                                <br>
                                                <button type="submit"><span>Login</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div id="lg2" class="tab-pane">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            {{ user_form.as_p }}

                                            <!-- <input type="text" name="user-name" placeholder="Username" />
                                            <br>
                                            <br>
                                            <input type="password" name="user-password" placeholder="Password" />
                                            <br>
                                            <br>
                                            <input name="user-email" placeholder="Email" type="email" /> -->
                                            <div class="button-box">
                                                <br>
                                                <button type="submit"><span>Register</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- login area end -->



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

managerproject/managerproject/managerapp/templates/main/tasks_list.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>task management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary bg-gradient ">
        <div class="container-fluid">
          <a class="navbar-brand fw-bold text-white fs-3" href="#">task management system</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'managerapp:Create-Task' %}">create a task</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'managerapp:account' %}">Logout</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled fw-medium" aria-disabled="true">Disabled</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
    </nav>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Assigned person</th>
            </tr>
        </thead>

        <tbody>

        </tbody>
    </table>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

managerproject/managerproject/project/templates/project/add.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>task management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary bg-gradient ">
        <div class="container-fluid">
          <a class="navbar-brand fw-bold text-white fs-3" href="#">task management system</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="#">create a task</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'managerapp:account' %}">Logout</a>
              </li> {% endcomment %}
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled fw-medium" aria-disabled="true">Disabled</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
    </nav>

    <main class="py-6 px-8 p-3">
        <h1 class="mb-5 text-1xl p-3">Projects</h1>

        <form action="#"  method="post" action=".">
            {% csrf_token %}
            <div class="mb-3 mt-3">
              <label for="email">Name</label>
              <input type="text" class="form-control"  name="name">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Description</label>
                <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>

    </main>
    



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

managerproject/managerproject/project/templates/project/projects.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>task management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary bg-gradient ">
        <div class="container-fluid">
          <a class="navbar-brand fw-bold text-white fs-3" href="#">task management system</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="#">create a task</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fw-medium fs-4" href="{% url 'managerapp:account' %}">Logout</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled fw-medium" aria-disabled="true">Disabled</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
    </nav>

    <main class="py-6 px-8 p-3">
        <h1 class="mb-5 text-1xl p-3">Projects</h1>
    
        
        <a href="{% url 'project:add' %}" class="btn btn-primary">Add project</a>
    
        {% comment %} <div class="mt-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <div class="py-6 px-6 bg-gray-200">
                <h2 class="mb-4 text-xl mt-3">Project title</h2>
                <p class="text-sm text-gray-600">Short project description. Short project description. Short project description.</p>
            </div>
    
            <!-- Repeat the above div for each project -->
        </div> {% endcomment %}
       
    
          <div class="row">
            <div class="col-sm-6 mb-3 mb-sm-0 mt-4">
              <div class="card">
                {% for project in projects %}
                <div class="card-body">
                  <a href="">
                      <h5 class="card-title">{{ project.name }}</h5>
                      <p class="card-text">{{ project.description }}</p>
                  </a>
              </div>
                {% endfor %}  <!-- Close the for loop here -->
              </div>
            </div>

            {% comment %} <div class="col-sm-6 mt-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Special title treatment</h5>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                </div>
              </div>
             </div> {% endcomment %}
           </div>
    </main>
    




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>